package application;

import javafx.fxml.FXML;

import javafx.scene.text.Text;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class direct1Controller {
	@FXML
	private Text seconds_chrono;
	@FXML
	private ImageView start_chrono;
	@FXML
	private ImageView pause_chrono;
	@FXML
	private Text minutes_chrono;

	// Event Listener on ImageView[#start_chrono].onMouseClicked
	@FXML
	public void startChrono(MouseEvent event) throws InterruptedException {
		int seconds = 0;
		int minutes = 0;
		
		while(seconds < 60 && minutes < 60) {
			System.out.print("courcou");
			Thread.sleep(1000);
			seconds+=seconds;
			if(seconds < 10) {
				seconds_chrono.setText("0");
			}
			seconds_chrono.setText(Integer.toString(seconds));
			if(seconds == 60) {
				minutes+=minutes;
				if(minutes < 10) {
					seconds_chrono.setText("0" + Integer.toString(minutes));
				}
				minutes_chrono.setText(Integer.toString(minutes));
				seconds=0;
			}
		}
	}
	// Event Listener on ImageView[#pause_chrono].onMouseClicked
	@FXML
	public void pauseChrono(MouseEvent event) {
		// TODO Autogenerated
	}
}
